# apps/presupuesto/models/core.py
from django.db import models
from .core_catalogos import Programa

class Proyecto(models.Model):
    id = models.AutoField(primary_key=True)
    codigo = models.CharField(max_length=100, null=True, blank=True)
    nombre = models.TextField(null=True, blank=True)

    programa = models.ForeignKey(
        Programa,
        db_column="programa_id",
        on_delete=models.DO_NOTHING,
        related_name="proyectos",
        null=True, blank=True
    )

    subgrupo = models.ForeignKey(
        'login.Subgrupo',
        on_delete=models.DO_NOTHING,
        db_column='subgrupo_id',
        null=True, blank=True
    )

    @property
    def dependencia(self):
        return self.subgrupo.dependencia if self.subgrupo_id else None

    class Meta:
        db_table = 'proyecto'
        managed = False

    def __str__(self):
        cod = self.codigo or self.id
        nom = (self.nombre or '').strip()
        return f"{cod} — {nom[:60]}" if nom else f"{cod}"


class Actividad(models.Model):
    id = models.BigAutoField(primary_key=True)
    nombre = models.TextField()

    class Meta:
        managed = False
        db_table = "actividad"      # <-- sin 'public.'
        ordering = ["nombre"]

    def __str__(self):
        return (self.nombre or '').strip() or f"Actividad #{self.id}"


class ActividadPlan(models.Model):
    id = models.BigAutoField(primary_key=True)
    proyecto = models.ForeignKey(Proyecto, db_column="proyecto_id",
                                 on_delete=models.DO_NOTHING)
    # si existe en BD, añadimos el FK a catálogo de actividades:
    actividad = models.ForeignKey(
        Actividad, db_column="actividad_id",
        on_delete=models.DO_NOTHING, null=True, blank=True
    )
    descripcion = models.TextField()

    class Meta:
        managed = False
        db_table = "actividad_plan"   # <-- sin 'public.'
        unique_together = (("proyecto", "descripcion"),)
        indexes = [
            # Índice declarativo (P4): existe en BD via DDL externo.
            models.Index(fields=["proyecto"], name="idx_actividad_plan_proyecto"),
        ]

    def __str__(self):
        desc = (self.descripcion or '').strip()
        return f"#{self.id} {desc[:80]}" if desc else f"#{self.id}"

class FormaPago(models.Model):
    """Catálogo de formas de pago. La TABLA ya existía (vacía); el DDL 013 la
    sembró con cinco filas internas.

    Los códigos van en 901+ a propósito. La fuente de verdad es BogData
    (decisión de Alex, 2026-08-24) y hoy no hay acceso técnico, así que el área
    captura mientras tanto. Si estas filas fueran 1..5 y BogData trajera sus
    códigos 1..N con otro significado, la corrupción sería silenciosa: mismo
    número, distinto sentido. Con el rango separado, sus códigos entran sin
    pisar nada y se puede mapear.
    """
    codigo = models.IntegerField(primary_key=True, db_column="codigo")
    nombre = models.TextField(db_column="nombre")

    class Meta:
        managed = False
        db_table = "forma_pago"
        ordering = ["codigo"]
        verbose_name = "Forma de pago"
        verbose_name_plural = "Formas de pago"

    def __str__(self):
        return self.nombre


class EtapaContrato(models.Model):
    """Catálogo de las 4 etapas contractuales (DDL 010, aplicado 2026-08-23).

    Es catálogo PROPIO y no `fase_proyecto` por una razón medida: `fase_proyecto`
    es de PROYECTO y tiene 3 filas (Planeación / Ejecución / Cierre). Meterle una
    cuarta fila para «Sancionatorio» contaminaría un catálogo de otra cosa.

    `orden` manda en el stepper: no se infiere del código ni del nombre.
    """
    codigo = models.SmallIntegerField(primary_key=True, db_column="codigo")
    nombre = models.CharField(max_length=30, unique=True, db_column="nombre")
    orden = models.SmallIntegerField(db_column="orden")
    descripcion = models.TextField(null=True, blank=True, db_column="descripcion")

    class Meta:
        managed = False
        db_table = "etapa_contrato"
        ordering = ["orden"]
        verbose_name = "Etapa contractual"
        verbose_name_plural = "Etapas contractuales"

    def __str__(self):
        return self.nombre


class Contrato(models.Model):
    # ⚠️ CORREGIDO 2026-08-27: la «deuda S5» NO existe en esta tabla.
    #
    # Aquí decía que `contrato.id` no tiene secuencia y que insertar exige el
    # fallback MAX(id)+1. Es falso, y lo era desde hace tiempo: la columna es
    # `GENERATED BY DEFAULT AS IDENTITY` con la secuencia `contrato_id_seq`.
    # Comprobado con un INSERT real omitiendo `id` dentro de una transacción
    # revertida: le asignó el 386 (`last_value`=386 contra `MAX(id)`=105).
    #
    # El campo sigue siendo `IntegerField` A PROPÓSITO, no por inercia:
    # cambiarlo a `AutoField` altera el comportamiento de los cuatro sitios que
    # insertan contratos, y eso es un cambio aparte con sus propias pruebas. Lo
    # que NO hay que hacer es seguir copiando el MAX(id)+1 «porque no hay
    # secuencia»: sí la hay. Y ojo con el efecto lateral de los ids explícitos,
    # que no la avanzan — hoy va en 386 y los ids en 105.
    id = models.IntegerField(primary_key=True)
    contrato_tipo = models.TextField()
    # NULLABLE EN LA BASE (DDL 016) y obligatorio acá, y la discrepancia es
    # deliberada mientras dure la transición. NO «arreglar» poniendo null=True.
    #
    # El 016 relajó la columna para el contrato «en elaboración», que ya no va a
    # existir: por decisión del 2026-08-26 esa etapa sale del dominio del
    # contrato y pasa al dominio FORMULACIÓN (`specs/004-formulacion/plan.md`).
    # Cuando ese dominio exista, el 016 se revierte y la columna vuelve a NOT
    # NULL — en el mismo cambio, nunca antes, o el contrato que todavía no tiene
    # número se queda sin dónde vivir.
    #
    # Mientras tanto: los 25 contratos tienen número, ningún endpoint crea sin
    # él, y `uq_contrato_tripleta` deja de proteger justo en las filas con
    # número NULL (PostgreSQL trata cada NULL como distinto). Por eso el modelo
    # se queda del lado estricto.
    contrato_numero = models.IntegerField()
    contrato_vigencia = models.IntegerField()
    objeto = models.TextField(null=True, blank=True)

    # Campos sueltos sin FK formal (para no introducir dependencias nuevas)
    tipo_contrato = models.IntegerField(null=True, blank=True)
    funcionario = models.IntegerField(null=True, blank=True)
    proveedor_id = models.IntegerField(null=True, blank=True)

    # Campos PR-H3 (DDL aplicado por sesión principal 2026-04-25)
    fecha_inicio = models.DateField(null=True, blank=True)
    fecha_fin = models.DateField(null=True, blank=True)
    valor = models.DecimalField(max_digits=18, decimal_places=4, null=True, blank=True)

    # PR contrato-cdp-saldo (DDL aplicado): FK opcional al CDP que financia el contrato.
    cdp = models.ForeignKey(
        'presupuesto.Cdp',
        on_delete=models.SET_NULL,
        null=True, blank=True,
        db_column='cdp_id',
        related_name='contratos',
    )

    # Contratos de infraestructura (DDL 004, 2026-06-22). Aditivos, nullable.
    categoria = models.CharField(max_length=20, null=True, blank=True)  # VIAS/PARQUES/INTERVENTORIA
    proyecto_codigo = models.CharField(max_length=10, null=True, blank=True)
    proyecto_nombre = models.TextField(null=True, blank=True)
    ejecucion = models.SmallIntegerField(null=True, blank=True)  # % 0-100
    interventoria_contrato = models.CharField(max_length=30, null=True, blank=True)
    interventoria_valor = models.DecimalField(max_digits=18, decimal_places=4,
                                              null=True, blank=True)

    # ── Etapa contractual (DDL 010, aplicado 2026-08-23) ──────────────────
    # Las tres van juntas a propósito: este dato lo escribe UNA PERSONA sobre
    # información contractual, así que sin fecha ni autor no hay auditoría y el
    # dato no vale. NULL en `etapa` = «pendiente de registrar» (medido: 25 de 25
    # hoy). NUNCA se asume «Ejecución» por defecto: SECOP dice «Modificado» en
    # 20 de nuestros 25 contratos, y eso significa que hubo otrosí, no una etapa.
    etapa = models.ForeignKey(
        EtapaContrato,
        on_delete=models.DO_NOTHING,
        null=True, blank=True,
        db_column="etapa_codigo",
        related_name="contratos",
    )
    etapa_fecha = models.DateTimeField(null=True, blank=True, db_column="etapa_fecha")
    etapa_usuario = models.ForeignKey(
        "login.Usuario",
        on_delete=models.DO_NOTHING,
        null=True, blank=True,
        db_column="etapa_usuario_id",
        related_name="contratos_etapa_registrada",
    )

    # ── Forma de pago (DDL 013, aplicado 2026-08-24) ──────────────────────
    # Mismas tres columnas que la etapa, y por el mismo motivo: lo escribe una
    # persona sobre información contractual, así que sin fecha ni autor el dato
    # no se puede defender. NULL = «pendiente por diligenciar»; nunca se asume
    # una forma de pago por defecto.
    #
    # La fuente de verdad es BogData, vía `crp.forma_pago_codigo`. Mientras no
    # haya acceso, esto es la captura del área — y cuando llegue el CRP, la
    # precedencia dice que manda la fuente oficial.
    forma_pago = models.ForeignKey(
        FormaPago,
        on_delete=models.DO_NOTHING,
        null=True, blank=True,
        db_column="forma_pago_codigo",
        related_name="contratos",
    )
    forma_pago_fecha = models.DateTimeField(null=True, blank=True,
                                            db_column="forma_pago_fecha")
    forma_pago_usuario_id = models.IntegerField(null=True, blank=True,
                                                db_column="forma_pago_usuario_id")

    class Meta:
        managed = False
        db_table = "contrato"
        ordering = ["-contrato_vigencia", "-contrato_numero"]

    def __str__(self):
        return f"{self.contrato_tipo or ''} {self.contrato_numero}/{self.contrato_vigencia}"


class ContratoProyecto(models.Model):
    # N3 (2026-05-11): tabla tiene `id BIGSERIAL UNIQUE` aparte de la PK
    # compuesta (contrato_id, proyecto_id). Antes Django mapeaba `contrato`
    # como PK lógica, perdiendo filas si un contrato tuviera >1 proyecto.
    id = models.BigAutoField(primary_key=True)
    contrato = models.ForeignKey(Contrato, db_column="contrato_id",
                                 on_delete=models.DO_NOTHING,
                                 related_name="contrato_proyectos")
    proyecto = models.ForeignKey(Proyecto, db_column="proyecto_id",
                                 on_delete=models.DO_NOTHING,
                                 related_name="contrato_proyectos")
    class Meta:
        managed = False
        db_table = "contrato_proyecto"
        unique_together = (("contrato", "proyecto"),)


class ContratoActividad(models.Model):
    # N3 (2026-05-11): mismo fix que ContratoProyecto. En esta tabla el
    # bug latente ya se materializaba — contrato_id=1 y =16 tienen 2
    # actividades cada uno, y el ORM solo veía la primera.
    id = models.BigAutoField(primary_key=True)
    contrato = models.ForeignKey(Contrato, db_column="contrato_id",
                                 on_delete=models.DO_NOTHING)
    actividad = models.ForeignKey(Actividad, db_column="actividad_id",
                                  on_delete=models.DO_NOTHING)
    class Meta:
        managed = False
        db_table = "contrato_actividad"
        unique_together = (("contrato", "actividad"),)


class TramoVialContrato(models.Model):
    """Tramo vial intervenido por un contrato (DDL 004). La geometría real
    (LineString GeoJSON) se cachea en `geom` desde la Malla Vial Integral
    consultando por `civ`. `geo_status` indica si se resolvió."""
    OK, NO_ENCONTRADO, FALLBACK, PENDIENTE = "OK", "NO_ENCONTRADO", "FALLBACK", "PENDIENTE"

    id = models.BigAutoField(primary_key=True)
    contrato = models.ForeignKey(Contrato, db_column="contrato_id",
                                 on_delete=models.CASCADE,
                                 related_name="tramos_viales")
    civ = models.BigIntegerField(null=True, blank=True)
    pk_id = models.BigIntegerField(null=True, blank=True)
    eje_vial = models.TextField(null=True, blank=True)
    desde = models.TextField(null=True, blank=True)
    hasta = models.TextField(null=True, blank=True)
    valor_intervencion = models.DecimalField(max_digits=18, decimal_places=4,
                                             null=True, blank=True)
    pct_avance = models.SmallIntegerField(default=0)
    geom = models.JSONField(null=True, blank=True)  # GeoJSON LineString
    geo_status = models.CharField(max_length=15, default=PENDIENTE)
    created_at = models.DateTimeField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        managed = False
        db_table = "tramo_vial_contrato"
        unique_together = (("contrato", "civ"),)


class IntervencionParque(models.Model):
    """Intervención de un parque por un contrato (DDL 004). Reusa la tabla
    `parque` existente (con geometría); aquí solo el puente parque↔contrato
    con su % de avance. El parque 08-742 aparece en 2 contratos = 2 filas."""
    id = models.BigAutoField(primary_key=True)
    parque = models.ForeignKey("georeferenciacion.Parque", db_column="parque_id",
                               on_delete=models.DO_NOTHING,
                               related_name="intervenciones")
    contrato = models.ForeignKey(Contrato, db_column="contrato_id",
                                 on_delete=models.CASCADE,
                                 related_name="intervenciones_parque")
    pct_avance = models.SmallIntegerField(default=0)
    # Dirección de la intervención (planilla del contrato). El nombre/geometría
    # del parque vienen de la tabla `parque`.
    direccion = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        managed = False
        db_table = "intervencion_parque"
        unique_together = (("parque", "contrato"),)


class CorteAvanceObra(models.Model):
    """Corte de avance de obra (DDL 006) — historial minucioso. Aplica a un
    contrato completo (interventoría), una vía (tramo) o un parque. Cada corte:
    fecha, %, observación, evidencia (foto cifrada en Mongo) y autor."""
    CONTRATO, TRAMO, PARQUE = "contrato", "tramo", "parque"

    id = models.BigAutoField(primary_key=True)
    contrato = models.ForeignKey(Contrato, db_column="contrato_id",
                                 on_delete=models.CASCADE, related_name="cortes")
    objeto_tipo = models.CharField(max_length=10)   # contrato | tramo | parque
    objeto_id = models.BigIntegerField(null=True, blank=True)
    fecha = models.DateField()
    pct = models.SmallIntegerField(default=0)
    observacion = models.TextField(null=True, blank=True)
    foto_antes_mongo_id = models.CharField(max_length=64, null=True, blank=True)
    foto_despues_mongo_id = models.CharField(max_length=64, null=True, blank=True)
    autor_id = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        managed = False
        db_table = "corte_avance_obra"
        ordering = ["-fecha", "-id"]
