"""Modelos del módulo Banco de Iniciativas Recreodeportivas.

Todos los modelos son `managed = False` (BD externa, schema gestionado
por DDL aplicado fuera de Django). El proyecto numero corresponde al
'2784 — Banco de Iniciativas' de la Alcaldía Local de Kennedy.
"""
from .catalogos import (
    Upl,
    TipoOrganizacion,
    RangoExperiencia,
    Escenario,
    Implemento,
    RangoPoblacionAtendida,
    RangoEtario,
    CaracteristicaPoblacion,
    EnfoqueDiferencial,
    TipoBeneficioAlk,
    DisciplinaDeportiva,
    Red,
    TipoApoyo,
    CategoriaMaterial,
    # Lote 4 — dedicados
    EnfoquePropuesta,
    TipoHabitabilidadCalle,
    TipoDesplazamiento,
    TipoPoblacionRural,
    GrupoEtnicoBanco,
    IdentidadGeneroBanco,
    # Lote 4 — genéricos reusados
    TipoDiscapacidad,
    OrientacionSexual,
)
from .inscripcion import (
    InscripcionBancoIniciativa,
    InscripcionBancoEscenario,
    InscripcionBancoEscenarioActual,
    InscripcionBancoImplemento,
    InscripcionBancoRangoEtario,
    InscripcionBancoEnfoque,
    InscripcionBancoBeneficioAlk,
    InscripcionBancoCicloVital,
    InscripcionBancoEntornoRed,
    InscripcionBancoTipoApoyo,
    InscripcionBancoCategoriaMaterial,
    # Lote 4 — puentes
    InscripcionBancoDiscapacidad,
    InscripcionBancoOrientacionSexual,
    InscripcionBancoIdentidadGenero,
    InscripcionBancoGrupoEtnico,
    InscripcionBancoEnfoquePropuesta,
    InscripcionBancoHabitabilidad,
    InscripcionBancoDesplazamiento,
    InscripcionBancoPoblacionRural,
    # Lote 3 — puente con datos
    InscripcionBancoRedDetalle,
)

__all__ = [
    "Upl",
    "TipoOrganizacion",
    "RangoExperiencia",
    "Escenario",
    "Implemento",
    "RangoPoblacionAtendida",
    "RangoEtario",
    "CaracteristicaPoblacion",
    "EnfoqueDiferencial",
    "TipoBeneficioAlk",
    "DisciplinaDeportiva",
    "Red",
    "TipoApoyo",
    "CategoriaMaterial",
    "EnfoquePropuesta",
    "TipoHabitabilidadCalle",
    "TipoDesplazamiento",
    "TipoPoblacionRural",
    "GrupoEtnicoBanco",
    "IdentidadGeneroBanco",
    "TipoDiscapacidad",
    "OrientacionSexual",
    "InscripcionBancoIniciativa",
    "InscripcionBancoEscenario",
    "InscripcionBancoEscenarioActual",
    "InscripcionBancoImplemento",
    "InscripcionBancoRangoEtario",
    "InscripcionBancoEnfoque",
    "InscripcionBancoBeneficioAlk",
    "InscripcionBancoCicloVital",
    "InscripcionBancoEntornoRed",
    "InscripcionBancoTipoApoyo",
    "InscripcionBancoCategoriaMaterial",
    "InscripcionBancoDiscapacidad",
    "InscripcionBancoOrientacionSexual",
    "InscripcionBancoIdentidadGenero",
    "InscripcionBancoGrupoEtnico",
    "InscripcionBancoEnfoquePropuesta",
    "InscripcionBancoHabitabilidad",
    "InscripcionBancoDesplazamiento",
    "InscripcionBancoPoblacionRural",
    "InscripcionBancoRedDetalle",
]
