# Generated by Django 4.2.11 on 2025-06-17 21:02

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_funcionario', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccesoSalud',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'acceso_salud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AfiliacionSalud',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'afiliacion_salud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalidadAccesoSalud',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calidad_acceso_salud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactoPersona',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('telefono_principal', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contacto_persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dependencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'eps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoEtario',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grupo_etario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoEtnico',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grupo_etnico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IdentidadGenero',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'identidad_genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LugarNacimiento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('persona_id', models.IntegerField(blank=True, null=True)),
                ('municipio_codigo', models.IntegerField(blank=True, null=True)),
                ('pais_codigo', models.IntegerField(blank=True, null=True)),
                ('departamento_codigo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lugar_nacimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nivel_educativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_ocupacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ocupacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrientacionSexual',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orientacion_sexual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=100)),
                ('nombre2', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True)),
                ('pertenencia_lgbti', models.BooleanField(null=True)),
                ('discapacidad', models.BooleanField(null=True)),
                ('rol_cuidador', models.BooleanField(null=True)),
                ('victima_conflicto', models.BooleanField(null=True)),
                ('migrante', models.BooleanField(null=True)),
                ('poblacion_rural', models.BooleanField(null=True)),
                ('estrato_social', models.SmallIntegerField(blank=True, null=True)),
                ('actualmente_estudia', models.BooleanField(null=True)),
                ('institucion', models.CharField(blank=True, max_length=255, null=True)),
                ('ingresos_mensuales', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_personas_hogar', models.SmallIntegerField(blank=True, null=True)),
                ('acceso_internet', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('usuario_editor', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonaDocumento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_documento', models.TextField()),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'persona_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectorEconomico',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sector_economico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sexo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'subgrupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoConstruccion',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_construccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDiscapacidad',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'tipo_discapacidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoFuncionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoVictima',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_victima',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zona',
                'managed': False,
            },
        ),
    ]
